import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import Headbarcompo from "./components/Headbarcompo";
import { Sidebar } from "./components/Sidebar";
import TabSwitcher from "./components/Tabswitchcompo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}>
        {/* Sidebar */}
        <aside className="fixed inset-y-0 left-0 w-64">
          <Sidebar />
        </aside>

        {/* Main content */}
        <div className="ml-64 relative flex flex-col h-screen">
          <Header />
          <div className="flex-1 overflow-auto">
            <div className="max-w-full">
              <Headbarcompo />
              <TabSwitcher />
              <main className="px-6">
                <div className="max-w-[calc(100vw-16rem)]">
                  {children}
                </div>
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
