import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import Headbarcompo from "./components/Headbarcompo";
import { Sidebar } from "./components/Sidebar";
import TabSwitcher from "./components/Tabswitchcompo";
import SidebarWrapper from "./components/Sidebarwrap";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Task2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en" className="h-full">
  <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}>
    <aside className="hidden md:block fixed inset-y-0 left-0 w-64 z-40 bg-white">
      <Sidebar />
    </aside>
    <SidebarWrapper/>

    <div className="relative flex flex-col h-screen md:ml-64">
      <Header />
      <div className="flex-1 overflow-auto">
        <div className="max-w-full">
          <Headbarcompo />
          <TabSwitcher />
          <main className="px-4 sm:px-6 md:px-8">
            <div className="max-w-full md:max-w-[calc(100vw-16rem)]">
              {children}
            </div>
          </main>
        </div>
      </div>
    </div>
  </body>
</html>

  );
}
